import { reactConfig } from '@friday/config/eslint/react';
import { routeHandlerBoundary } from '@friday/config/eslint/boundaries';

/**
 * apps/web is the composition root, so it may import every workspace package.
 * The one boundary that still applies inside it: route handlers may not reach
 * for repositories directly (SYSTEM_ARCHITECTURE §6.1).
 */
export default reactConfig('@friday/web', {
  extraConfigs: [
    // Generated by Next on every build; not ours to lint.
    { ignores: ['next-env.d.ts', '.next/**'] },
    routeHandlerBoundary(),
  ],
});
