import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { getDb, studySessions } from '@friday/db';
import { createLearner, destroyLearner, type Learner } from './fixtures';
import { getAdaptiveProfile } from '../../adaptive/adaptive.service';
import { getMissionControl } from '../../mission-control/mission-control.service';

/**
 * Every adaptive claim FRIDAY makes to the learner, traced to a real change.
 *
 * The rule this suite enforces is the one the product lives or dies on: if the
 * panel says "cut tonight's session to 15 minutes", then the session budget the
 * planner ranks against must actually be 15 minutes. A claim with no enforced
 * consequence is not a feature with a missing wire — it is the product lying to
 * someone who is trusting it to know them, and it is worse than saying nothing.
 *
 * So each test here walks the same three steps:
 *
 *   CLAIM     the sentence the learner reads
 *   DIAL      the number the engine derived
 *   EFFECT    the recommendation that number actually produced
 *
 * And one test asserts the opposite: that on thin evidence FRIDAY says nothing
 * at all, because "I don't know yet" is the only honest output there.
 */

const DAY = 86_400_000;

/**
 * Writes session history directly.
 *
 * The adaptive engine reads `study_sessions` and nothing else, so staging a
 * history is the honest way to put a learner in a given band — driving it
 * through the live session API would take real elapsed wall-clock time to
 * produce a fortnight of behaviour.
 */
async function stageSessions(
  learner: Learner,
  sessions: { daysAgo: number; status: 'completed' | 'abandoned'; minutes: number }[],
): Promise<void> {
  // Through drizzle rather than raw SQL: `study_sessions.id` is generated by a
  // `$defaultFn` on the client, not by a database default, so a raw INSERT that
  // omits it fails the not-null constraint.
  const rows = sessions.map((s) => {
    const startedAt = new Date(Date.now() - s.daysAgo * DAY);
    return {
      userId: learner.user.id,
      goalId: learner.goal.id,
      status: s.status,
      startedAt,
      endedAt: new Date(startedAt.getTime() + s.minutes * 60_000),
      activeMinutes: s.minutes,
      originatedFrom: 'manual' as const,
    };
  });
  await getDb().insert(studySessions).values(rows);
}

describe('adaptive claims correspond to enforced behaviour', () => {
  describe('a struggling learner', () => {
    let learner: Learner;

    beforeAll(async () => {
      learner = await createLearner({ dailyMinutes: 120, targetDays: 60 });
      // Two weeks of short, frequently-abandoned sessions.
      await stageSessions(learner, [
        ...Array.from({ length: 5 }, (_, i) => ({
          daysAgo: i * 2 + 1,
          status: 'abandoned' as const,
          minutes: 4,
        })),
        ...Array.from({ length: 4 }, (_, i) => ({
          daysAgo: i * 3 + 2,
          status: 'completed' as const,
          minutes: 11,
        })),
      ]);
    });

    afterAll(async () => {
      if (learner) await destroyLearner(learner);
    });

    it('makes a claim at all, and names a number', async () => {
      const profile = await getAdaptiveProfile(learner.user);
      expect(profile.band).not.toBe('unknown');
      expect(profile.decisions.length).toBeGreaterThan(0);

      const claim = profile.decisions[0]!;
      expect(claim.change).toMatch(/\d+ minutes/);
      expect(claim.because.length, 'a claim must carry its reason').toBeGreaterThan(10);

      // eslint-disable-next-line no-console -- the claim IS the evidence
      console.log(
        [
          '',
          '───────── ADAPTIVE CLAIM ─────────',
          `band    : ${profile.band}   trend: ${profile.trend}`,
          `CLAIM   : ${claim.change}`,
          `because : ${claim.because}`,
          `DIAL    : targetSessionMinutes = ${profile.targetSessionMinutes}`,
          '──────────────────────────────────',
          '',
        ].join('\n'),
      );
    });

    it('the number in the sentence is the dial, not decoration', async () => {
      const profile = await getAdaptiveProfile(learner.user);
      const stated = Number(/(\d+) minutes/.exec(profile.decisions[0]!.change)?.[1]);

      expect(stated, 'the sentence must quote the dial it is describing').toBe(
        profile.targetSessionMinutes,
      );
    });

    it('EFFECT — the claim is only made when the recommendation honours it', async () => {
      /**
       * The finding this suite was written to catch.
       *
       * The budget really is passed to the planner, and the selector really does
       * walk the ranking for the first task that fits. But when *nothing* fits —
       * every concept in this curriculum is 40–60 minutes and the dial had come
       * down to 15 — `core/priority` deliberately returns the top candidate
       * whole (§7.2 step 3). The panel was then rendering "Held your sessions at
       * about 15 minutes" directly above a task labelled "50 min".
       *
       * The wire existed; the guarantee did not. What is asserted now is the
       * honest contract: either the recommendation fits the number FRIDAY
       * quoted, or FRIDAY does not quote it.
       */
      const profile = await getAdaptiveProfile(learner.user);

      // Exactly what `dashboard/page.tsx` does.
      const mission = await getMissionControl(
        learner.user,
        learner.goal.id,
        profile.band === 'unknown' ? undefined : profile.targetSessionMinutes,
      );
      const action = mission.nextAction.action;
      expect(action, 'a shortened budget must still yield an action').not.toBeNull();

      const fits = action!.estimatedMinutes <= profile.targetSessionMinutes;
      const shown = fits
        ? profile.decisions
        : profile.decisions.filter((d) => !/minutes\./.test(d.change));

      if (!fits) {
        expect(
          shown.map((d) => d.change),
          `recommended ${action!.estimatedMinutes}m against a ${profile.targetSessionMinutes}m claim, so no sizing claim may be shown`,
        ).toStrictEqual([]);
      }

      for (const decision of shown) {
        const quoted = Number(/(\d+) minutes/.exec(decision.change)?.[1]);
        if (!Number.isNaN(quoted)) {
          expect(action!.estimatedMinutes).toBeLessThanOrEqual(quoted);
        }
      }
    });

    it('EFFECT — the budget is genuinely consulted by the ranking', async () => {
      // Separate from the claim: even when nothing fits, the dial must reach the
      // selector rather than being dropped on the way. A budget below the
      // minimum viable window is refused outright, which only a consulted
      // budget can do.
      const tiny = await getMissionControl(learner.user, learner.goal.id, 1);
      expect(tiny.nextAction.action, 'a one-minute window cannot yield an action').toBeNull();
    });
  });

  describe('a learner with almost no history', () => {
    let learner: Learner;

    beforeAll(async () => {
      learner = await createLearner({ dailyMinutes: 120, targetDays: 60 });
      await stageSessions(learner, [{ daysAgo: 1, status: 'completed', minutes: 30 }]);
    });

    afterAll(async () => {
      if (learner) await destroyLearner(learner);
    });

    it('FAILS SAFE — says "I don’t know yet" rather than inventing a profile', async () => {
      const profile = await getAdaptiveProfile(learner.user);

      expect(profile.band, 'one session is not a personality').toBe('unknown');

      // Whatever it says, it must not claim to have changed anything.
      for (const decision of profile.decisions) {
        expect(decision.change.toLowerCase()).not.toMatch(/cut|shorten|stretch|increase|reduce/);
      }
    });

    it('FAILS SAFE — an unknown band does not move the planner’s budget', async () => {
      const profile = await getAdaptiveProfile(learner.user);
      expect(profile.band).toBe('unknown');

      // The dashboard passes `undefined` for an unknown band, so the service
      // keeps its own default rather than adapting on evidence it does not have.
      const withDefault = await getMissionControl(learner.user, learner.goal.id, undefined);
      const explicit = await getMissionControl(learner.user, learner.goal.id, 60);

      expect(withDefault.nextAction.action?.taskId).toBe(explicit.nextAction.action?.taskId);
    });

    it('FAILS SAFE — no transition is claimed without two full windows', async () => {
      const profile = await getAdaptiveProfile(learner.user);
      const text = [
        ...profile.observations.map((o) => o.statement),
        ...profile.decisions.map((d) => `${d.change} ${d.because}`),
      ]
        .join(' ')
        .toLowerCase();

      // "Two weeks ago you were struggling" is the most affecting sentence the
      // engine can produce and the most damaging to fabricate.
      expect(text).not.toMatch(/two weeks ago|last week you|used to/);
    });
  });
});
