import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { Sparkles } from 'lucide-react';
import { cn } from '../lib/cn';

const badgeVariants = cva(
  'inline-flex items-center gap-1 rounded-full border px-2.5 py-0.5 text-xs font-medium',
  {
    variants: {
      variant: {
        neutral: 'border-border bg-muted text-muted-foreground',
        primary: 'border-transparent bg-primary text-primary-foreground',
        success: 'border-transparent bg-success text-success-foreground',
        warning: 'border-transparent bg-warning text-warning-foreground',
        destructive: 'border-transparent bg-destructive text-destructive-foreground',
        outline: 'border-border-strong text-foreground',
        /** NFR-6.3: anything generated by a model is visibly labelled as such. */
        ai: 'border-transparent bg-ai-surface text-ai-accent',
      },
    },
    defaultVariants: { variant: 'neutral' },
  },
);

export interface BadgeProps
  extends React.HTMLAttributes<HTMLSpanElement>, VariantProps<typeof badgeVariants> {}

export function Badge({ className, variant, children, ...props }: BadgeProps) {
  return (
    <span className={cn(badgeVariants({ variant }), className)} {...props}>
      {variant === 'ai' && <Sparkles className="size-3" aria-hidden />}
      {children}
    </span>
  );
}

/**
 * The single, consistent marker for model-generated content. Centralised so the
 * treatment cannot drift between surfaces.
 */
export function AiBadge({ className }: { className?: string }) {
  return (
    <Badge variant="ai" className={className}>
      AI generated
    </Badge>
  );
}

export { badgeVariants };
